export const mockUsers = [
  {
    id: 1,
    name: "Admin User",
    email: "admin@example.com",
    password: "admin123",
    role: "admin",
    createdAt: "2023-01-01",
    profileImage: "https://i.pravatar.cc/150?img=4",
    status: "active",
  },
  {
    id: 2,
    name: "Manager User",
    email: "manager@example.com",
    password: "manager123",
    role: "manager",
    createdAt: "2023-01-02",
    profileImage: "https://i.pravatar.cc/150?img=2",
    status: "inactive",
  },
  {
    id: 3,
    name: "Viewer User",
    email: "viewer@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-03",
    profileImage: "https://i.pravatar.cc/150?img=3",
    status: "active",
  },
  {
    id: 4,
    name: "Viewer User 2",
    email: "viewer2@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-04",
    profileImage: "https://i.pravatar.cc/150?img=4",
    status: "active",
  },
  {
    id: 5,
    name: "Viewer User 3",
    email: "viewer3@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-05",
    profileImage: "https://i.pravatar.cc/150?img=5",
    status: "suspended",
  },
  {
    id: 6,
    name: "Viewer User 4",
    email: "viewer4@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-06",
    profileImage: "https://i.pravatar.cc/150?img=6",
    status: "active",
  },
  {
    id: 7,
    name: "Viewer User 5",
    email: "viewer5@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-07",
    profileImage: "https://i.pravatar.cc/150?img=7",
    status: "active",
  },
  {
    id: 8,
    name: "Viewer User 6",
    email: "viewer6@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-08",
    profileImage: "https://i.pravatar.cc/150?img=8",
    status: "active",
  },
  {
    id: 9,
    name: "Viewer User 7",
    email: "viewer7@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-09",
    profileImage: "https://i.pravatar.cc/150?img=9",
    status: "suspended",
  },
  {
    id: 10,
    name: "Viewer User 8",
    email: "viewer8@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-10",
    profileImage: "https://i.pravatar.cc/150?img=10",
    status: "active",
  },
  {
    id: 11,
    name: "Viewer User 9",
    email: "viewer9@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-11",
    profileImage: "https://i.pravatar.cc/150?img=11",
    status: "inactive",
  },
  {
    id: 12,
    name: "Viewer User 10",
    email: "viewer10@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-12",
    profileImage: "https://i.pravatar.cc/150?img=12",
    status: "active",
  },
  {
    id: 13,
    name: "Viewer User 11",
    email: "viewer11@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-13",
    profileImage: "https://i.pravatar.cc/150?img=13",
    status: "suspended",
  },
  {
    id: 14,
    name: "Viewer User 12",
    email: "viewer12@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-14",
    profileImage: "https://i.pravatar.cc/150?img=14",
    status: "active",
  },
  {
    id: 15,
    name: "Viewer User 13",
    email: "viewer13@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-15",
    profileImage: "https://i.pravatar.cc/150?img=15",
    status: "active",
  },
  {
    id: 16,
    name: "Viewer User 14",
    email: "viewer14@example.com",
    password: "viewer123",
    role: "viewer",
    createdAt: "2023-01-16",
    profileImage: "https://i.pravatar.cc/150?img=16",
    status: "active",
  },
];

export const usersTableHeadersAdmin = [
  { title: "Name", key: "name" },
  { title: "Email", key: "email" },
  { title: "Role", key: "role" },
  { title: "Joined", key: "createdAt" },
  { title: "Status", key: "status" },
  { title: "Actions", key: "actions", sortable: false },
];

export const usersTableHeadersViewer = [
  { title: "Name", key: "name" },
  { title: "Email", key: "email" },
  { title: "Role", key: "role" },
  { title: "Joined", key: "createdAt" },
];
export const usersTableData = mockUsers.map((user) => ({
  name: user.name,
  email: user.email,
  role: user.role,
  createdAt: user.createdAt,
  profileImage: user.profileImage,
}));

export const rolesFilterOptions = [
  { title: "all", value: null },
  { title: "admin", value: "admin" },
  { title: "manager", value: "manager" },
  { title: "viewer", value: "viewer" },
];

export const statusOptions = [
  { title: "all", value: null },
  { title: "active", value: "active" },
  { title: "inactive", value: "inactive" },
  { title: "suspended", value: "suspended" },
];
